// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exercise-items.sql

package repository

import (
	"context"
)

const createExerciseItemAndReturnId = `-- name: CreateExerciseItemAndReturnId :one
INSERT INTO exercise_items (
  id, type, user_id, workout_id, created_on, updated_on
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6
)
RETURNING id
`

type CreateExerciseItemAndReturnIdParams struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	UserID    string `json:"user_id"`
	WorkoutID string `json:"workout_id"`
	CreatedOn string `json:"created_on"`
	UpdatedOn string `json:"updated_on"`
}

func (q *Queries) CreateExerciseItemAndReturnId(ctx context.Context, arg CreateExerciseItemAndReturnIdParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createExerciseItemAndReturnId,
		arg.ID,
		arg.Type,
		arg.UserID,
		arg.WorkoutID,
		arg.CreatedOn,
		arg.UpdatedOn,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExerciseItemById = `-- name: DeleteExerciseItemById :execrows
DELETE FROM exercise_items
WHERE id = ?1
AND user_id = ?2
`

type DeleteExerciseItemByIdParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteExerciseItemById(ctx context.Context, arg DeleteExerciseItemByIdParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExerciseItemById, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getExerciseItemById = `-- name: GetExerciseItemById :one
SELECT id, type, user_id, workout_id, created_on, updated_on, "foreign" FROM exercise_items
WHERE id = ?1
AND user_id = ?2
`

type GetExerciseItemByIdParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetExerciseItemById(ctx context.Context, arg GetExerciseItemByIdParams) (ExerciseItem, error) {
	row := q.db.QueryRowContext(ctx, getExerciseItemById, arg.ID, arg.UserID)
	var i ExerciseItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.WorkoutID,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Foreign,
	)
	return i, err
}

const getExerciseItemsByWorkoutId = `-- name: GetExerciseItemsByWorkoutId :many
SELECT id, type, user_id, workout_id, created_on, updated_on, "foreign" FROM exercise_items
WHERE workout_id = ?1
AND user_id = ?2
ORDER BY created_on
`

type GetExerciseItemsByWorkoutIdParams struct {
	WorkoutID string `json:"workout_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetExerciseItemsByWorkoutId(ctx context.Context, arg GetExerciseItemsByWorkoutIdParams) ([]ExerciseItem, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseItemsByWorkoutId, arg.WorkoutID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseItem{}
	for rows.Next() {
		var i ExerciseItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.WorkoutID,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.Foreign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExerciseItemType = `-- name: UpdateExerciseItemType :execrows
UPDATE exercise_items
SET type = ?1, updated_on = ?2
WHERE id = ?3
AND user_id = ?4
`

type UpdateExerciseItemTypeParams struct {
	Type      string `json:"type"`
	UpdatedOn string `json:"updated_on"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateExerciseItemType(ctx context.Context, arg UpdateExerciseItemTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExerciseItemType,
		arg.Type,
		arg.UpdatedOn,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
