// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

type Exercise struct {
	ID             string
	Name           string
	WorkoutID      string
	ExerciseTypeID string
}

type ExerciseType struct {
	ID   string
	Name string
}

type Set struct {
	ID          string
	Repetitions int64
	Weight      float64
	ExerciseID  string
}

type Workout struct {
	ID        string
	Name      string
	Completed bool
	CreatedAt string
	UpdatedAt string
}
