// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	CompleteWorkoutById(ctx context.Context, arg CompleteWorkoutByIdParams) (int64, error)
	CreateExerciseAndReturnId(ctx context.Context, arg CreateExerciseAndReturnIdParams) (string, error)
	CreateExerciseTypeAndReturnId(ctx context.Context, arg CreateExerciseTypeAndReturnIdParams) (string, error)
	CreateSetAndReturnId(ctx context.Context, arg CreateSetAndReturnIdParams) (string, error)
	CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (string, error)
	CreateWorkoutAndReturnId(ctx context.Context, arg CreateWorkoutAndReturnIdParams) (string, error)
	DeleteExerciseById(ctx context.Context, id string) (int64, error)
	DeleteExerciseTypeById(ctx context.Context, id string) (int64, error)
	DeleteSetById(ctx context.Context, id string) (int64, error)
	GetAllExerciseTypes(ctx context.Context) ([]ExerciseType, error)
	GetAllExercises(ctx context.Context) ([]Exercise, error)
	GetAllSets(ctx context.Context) ([]Set, error)
	GetAllWorkouts(ctx context.Context) ([]Workout, error)
	GetExerciseById(ctx context.Context, id string) (Exercise, error)
	GetExerciseTypeById(ctx context.Context, id string) (ExerciseType, error)
	GetExercisesByWorkoutId(ctx context.Context, workoutID string) ([]Exercise, error)
	GetSetById(ctx context.Context, id string) (Set, error)
	GetSetsByExerciseId(ctx context.Context, exerciseID string) ([]Set, error)
	GetUserByUsernameAndPassword(ctx context.Context, arg GetUserByUsernameAndPasswordParams) (User, error)
	GetWorkoutById(ctx context.Context, id string) (Workout, error)
}

var _ Querier = (*Queries)(nil)
