// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sets.sql

package repository

import (
	"context"
)

const createSetAndReturnId = `-- name: CreateSetAndReturnId :one
INSERT INTO sets (
  id, repetitions, weight, exercise_id, created_on, updated_on
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6
)
RETURNING id
`

type CreateSetAndReturnIdParams struct {
	ID          string  `json:"id"`
	Repetitions int64   `json:"repetitions"`
	Weight      float64 `json:"weight"`
	ExerciseID  string  `json:"exercise_id"`
	CreatedOn   string  `json:"created_on"`
	UpdatedOn   string  `json:"updated_on"`
}

func (q *Queries) CreateSetAndReturnId(ctx context.Context, arg CreateSetAndReturnIdParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createSetAndReturnId,
		arg.ID,
		arg.Repetitions,
		arg.Weight,
		arg.ExerciseID,
		arg.CreatedOn,
		arg.UpdatedOn,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteSetById = `-- name: DeleteSetById :execrows
DELETE FROM sets 
where id = ?1
`

func (q *Queries) DeleteSetById(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSetById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllSets = `-- name: GetAllSets :many
SELECT id, repetitions, weight, created_on, updated_on, exercise_id FROM sets 
ORDER by id
`

func (q *Queries) GetAllSets(ctx context.Context) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getAllSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Set{}
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.Repetitions,
			&i.Weight,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.ExerciseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetById = `-- name: GetSetById :one
SELECT id, repetitions, weight, created_on, updated_on, exercise_id FROM sets 
WHERE id = ?1
`

func (q *Queries) GetSetById(ctx context.Context, id string) (Set, error) {
	row := q.db.QueryRowContext(ctx, getSetById, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.Repetitions,
		&i.Weight,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.ExerciseID,
	)
	return i, err
}

const getSetsByExerciseId = `-- name: GetSetsByExerciseId :many
SELECT id, repetitions, weight, created_on, updated_on, exercise_id FROM sets 
WHERE exercise_id = ?1
`

func (q *Queries) GetSetsByExerciseId(ctx context.Context, exerciseID string) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getSetsByExerciseId, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Set{}
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.Repetitions,
			&i.Weight,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.ExerciseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
