// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workouts.sql

package repositories

import (
	"context"
)

const countAllWorkouts = `-- name: CountAllWorkouts :one
SELECT COUNT(*) from workouts
`

func (q *Queries) CountAllWorkouts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllWorkouts)
	var count int64
	err := row.Scan(&count)
	return count, err
}
