name: Build Docker images

on:
  push:
    branches:
      - master

jobs:
  frontend:
    name: Build and lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm install --prefix ./frontend
      - run: npm run lint --prefix ./frontend
      - run: npm run build --prefix ./frontend


  backend:
    name: Build and test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        with:
          fetch-depth: 0
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: go build cmd/api/main.go 

      - name: Run Unit tests.
        run: go test ./...

  build-and-push-images:
    runs-on: ubuntu-latest
    needs:
      - frontend
      - backend
    steps:
      - name: Checkout repository
        with:
          fetch-depth: 0
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: backend
          push: true
          tags: |
            ghcr.io/jawee/gymotric-be:latest
            ghcr.io/jawee/gymotric-be:${{ github.sha }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: frontend
          push: true
          tags: |
            ghcr.io/jawee/gymotric-fe:latest
            ghcr.io/jawee/gymotric-fe:${{ github.sha }}

      - name: Build and push migrations
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.goose
          target: migrations
          push: true
          tags: |
            ghcr.io/jawee/gymotric-migrations:latest
            ghcr.io/jawee/gymotric-migrations:${{ github.sha }}
