name: CI

on:
  pull_request:

jobs:
  frontend:
    name: Build and lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm install --prefix ./frontend
      - run: npm run lint --prefix ./frontend
      - run: npm run build --prefix ./frontend


  backend:
    name: Build and test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        with:
          fetch-depth: 0
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: go build cmd/api/main.go 

      - name: Run Unit tests.
        run: go test ./...

  build-images:
    runs-on: ubuntu-latest
    needs:
      - frontend
      - backend
    steps:
      - name: Checkout repository
        with:
          fetch-depth: 0
        uses: actions/checkout@v4

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: backend
          push: false

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: frontend
          push: false

      - name: Build migrations image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.goose
          target: migrations
          push: false
